---
apiVersion: v1
kind: Pod
metadata:
  name: resultsapp-pod
  labels:
    name: resultsapp-pod
    author: skyda
spec:
  containers:
    - name: results-app
      image: dockersamples/examplevotingapp_result
      ports:
        - containerPort: 80
...