---
apiVersion: v1
kind: Service
metadata:
  name: resultapp-service
  labels:
    name: resultsapp-service
    author: skyda
spec:
  type: LoadBalancer
  ports:
    - targetPort: 80
      port: 80
  selector:
    name: resultsapp-pod
    author: skyda
...