---
apiVersion: v1
kind: Pod
metadata:
  name: votingapp-pod
  labels:
    name: votingapp-pod
    author: skyda
spec:
  containers:
    - name: voting-app
      image: dockersamples/examplevotingapp_vote
      ports:
        - containerPort: 80
...