---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: votingapp-deployment
  labels:
    name: votingapp-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      name: votingapp-deployment
  template:
    metadata:
      name: votingapp-pod
      labels:
        name: votingapp-deployment
    spec:
      containers:
        - name: votingapp
          image: dockersamples/examplevotingapp_vote
          ports:
            - containerPort: 80
...