---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workerapp-deployment
  labels:
    name: workerapp-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      name: workerapp-deployment
  template:
    metadata:
      name: workeapp-pod
      labels:
        name: workerapp-deployment
    spec:
      containers:
        - name: workerapp
          image: dockersamples/examplevotingapp_worker
          ports:
            - containerPort: 80
...