---
apiVersion: v1
kind: Pod
metadata:
  name: workerapp-pod
  labels:
    name: workerapp-pod
    author: skyda
spec:
  containers:
    - name: worker-app
      image: dockersamples/examplevotingapp_worker
...